# container management

default:
  @just --list

[no-cd]
[group('container')]
build:
    #!/usr/bin/env bash
    set -euxo pipefail
    version=$(cat version)
    echo deploying {{GREEN}}$version{{NORMAL}}
    podman build \
        -t docker.io/waylonwalker/reader-waylonwalker-com \
        -t docker.io/waylonwalker/reader-waylonwalker-com:$version \
        -t registry.wayl.one/reader-waylonwalker-com \
        -t registry.wayl.one/reader-waylonwalker-com:$version \
        -f container/Containerfile .


[no-cd]
[group('container')]
deploy:
    #!/usr/bin/env bash
    set -euxo pipefail
    version=$(cat version)
    echo deploying {{GREEN}}$version{{NORMAL}}
    podman push registry.wayl.one/reader-waylonwalker-com
    podman push registry.wayl.one/reader-waylonwalker-com:$version

[no-cd]
[group('container')]
ls:
    pwd
    ls
